# Generated by Django 4.2.4 on 2023-10-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_management_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("age", models.IntegerField(null=True)),
                ("address", models.TextField()),
                ("contact_number", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
