# Generated by Django 4.2.4 on 2023-10-09 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_management_app", "0002_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="name",
        ),
        migrations.AddField(
            model_name="patient",
            name="admin",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "Admin"), (2, "Patient"), (3, "Doctor")],
                default=1,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
