# Generated by Django 4.2.4 on 2023-10-10 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_management_app", "0003_remove_patient_name_patient_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="admin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
