# Generated by Django 4.2.4 on 2023-10-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_management_app", "0004_alter_patient_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
