# Generated by Django 4.2.4 on 2023-10-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_management_app", "0006_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="man",
            field=models.CharField(default="0", max_length=255),
        ),
    ]
