# Generated by Django 4.2.4 on 2023-10-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_management_app", "0010_customuser_email1_alter_customuser_email"),
    ]

    operations = [

    ]
