# Generated by Django 4.2.4 on 2023-10-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_management_app", "0011_remove_customuser_email1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(default="", max_length=255, unique=True),
        ),
    ]
