# Generated by Django 4.2.4 on 2023-10-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_management_app", "0012_alter_customuser_email"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="customuser",
        #     name="man",
        #     field=models.CharField(default="0", max_length=255),
        # ),
    ]
