# Generated by Django 4.2.4 on 2023-10-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_management_app", "0014_alter_doctor_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="profile_pic",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
