# Generated by Django 4.2.5 on 2023-11-03 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0018_patient_history_patient_room_id_patient_test_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='department',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_management_app.department'),
            preserve_default=False,
        ),
    ]
