# Generated by Django 4.2.5 on 2023-11-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0019_register_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_time',
            field=models.TextField(),
        ),
    ]
