# Generated by Django 4.2.7 on 2023-11-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0018_patient_is_prescript_patient_prescription_and_more'),
        ('hospital_management_app', '0020_alter_register_register_time'),
    ]

    operations = [
    ]
