# Generated by Django 4.2.5 on 2023-11-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0021_merge_20231106_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_members',
        ),
        migrations.AddField(
            model_name='room',
            name='room_members',
            field=models.ManyToManyField(to='hospital_management_app.staff'),
        ),
    ]
