# Generated by Django 4.2.5 on 2023-11-11 11:11

from django.db import migrations, models
import hospital_management_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0022_staff_department_intro_remove_room_room_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField(verbose_name=hospital_management_app.models.Patient)),
                ('doctor', models.IntegerField(verbose_name=hospital_management_app.models.Doctor)),
                ('department', models.IntegerField(verbose_name=hospital_management_app.models.Department)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('register_time', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
