# Generated by Django 4.2.5 on 2023-11-11 11:19

from django.db import migrations, models
import hospital_management_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0023_appointment_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.TextField(verbose_name=hospital_management_app.models.Department),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.TextField(verbose_name=hospital_management_app.models.Doctor),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.TextField(verbose_name=hospital_management_app.models.Patient),
        ),
    ]
