# Generated by Django 4.2.7 on 2023-11-13 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_management_app", "0022_alter_doctor_profile_pic"),
        ("hospital_management_app", "0024_alter_appointment_department_and_more"),
    ]

    operations = []
