# Generated by Django 4.2.7 on 2023-11-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_management_app", "0025_merge_20231113_2327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="profile_pic",
            field=models.FileField(null=True, upload_to="avatars"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="is_prescript",
            field=models.BooleanField(default="False"),
        ),
    ]
