# Generated by Django 4.2.6 on 2023-12-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0026_alter_doctor_profile_pic_alter_patient_is_prescript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_prescript',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_appointed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
