# Generated by Django 4.2.6 on 2023-12-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0027_remove_patient_is_prescript_and_more'),
    ]

