# Generated by Django 4.2.6 on 2023-12-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_management_app', '0028_remove_staff_is_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_members',
        ),
        migrations.AddField(
            model_name='room',
            name='nurse',
            field=models.TextField(null=True),
        ),
    ]
